# Generated by Django 5.2.8 on 2025-11-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('code', 'language', 'version')},
        ),
    ]
